name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4.1.1
    - name: install dependencies
      run: sudo apt install build-essential libarchive-dev qtbase5-private-dev qtbase5-dev libqt5svg5-dev libglibmm-2.4-dev libglib2.0-dev libpulse-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
    - name: mkdir
      run: mkdir build
    - name: cd build
      run: cd build
    - name: qmake
      run: qmake ../JDSP4Linux.pro "CONFIG += USE_PULSEAUDIO"
    - name: make
      run: make
    - name: upload artifacts
      uses: actions/upload-artifact@v4.3.0
      if: always()
      with:
        name: "jamesdsp"
        path: "build/src"
        if-no-files-found: ignore
#        retention-days: 20
